# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false

  http_client:
    scoped_clients:
      pokemonApi.client:
        base_uri: 'https://pokeapi.co'
        headers:
          Content-Type: 'application/json'
        retry_failed:
          http_codes:
            0: [ 'GET', 'HEAD' ]    # retry network errors if request method is GET or HEAD
            429: true               # retry all responses with 429 status code
            500: [ 'GET', 'HEAD' ]
          max_retries: 5
          delay: 1000
          multiplier: 3
          max_delay: 5000
          jitter: 0.3

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
