version: '3.7'
services:
  database:
    image: 'mariadb:10.6.4'
    volumes:
      - ${PWD}/docker-volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wise-pokemon
      MYSQL_DATABASE: wise-pokemon
      TZ: Europe\Brussels
    ports:
      - '3388:3306'
    labels:
      com.symfony.server.service-ignore: true
      com.symfony.server.service-prefix: 'NO'
